export const projectsData = [
  {
    "title": "Customer Spending Prediction Using Machine Learning",
    "slug": "customer-spending-prediction-machine-learning",
    "category": "AI/ML",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Basic",
    "starting_price": 999,
    "technologies": [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Matplotlib",
      "Seaborn",
      "Machine Learning",
      "Regression",
      "Streamlit"
    ],
    "short_description": "A machine learning system that predicts customer spending based on purchasing behavior, demographics, and historical transaction data.",
    "description": "Customer Spending Prediction is a machine learning project that analyzes historical customer information and purchasing patterns to estimate future spending. The system considers factors such as income, purchase frequency, transaction value, membership type, and previous spending behavior.",
    "problem_statement": "Businesses need to understand customer spending behavior to improve marketing strategies and customer engagement, but analyzing large amounts of customer data manually can be difficult.",
    "proposed_solution": "Develop a machine learning-based system that analyzes historical customer data and predicts estimated spending using relevant behavioral and demographic features.",
    "features": [
      "Customer data management",
      "Data preprocessing",
      "Customer behavior analysis",
      "Purchase frequency analysis",
      "Transaction analysis",
      "Customer spending prediction",
      "Regression model training",
      "Model evaluation",
      "Feature importance analysis",
      "Spending visualization",
      "Interactive prediction",
      "Dashboard"
    ],
    "architecture": "Customer data is collected and processed using Pandas and NumPy. Relevant features are selected and used to train regression models using Scikit-learn. The trained model predicts customer spending, while Streamlit provides an interactive interface for entering customer information and viewing results.",
    "seo_title": "Customer Spending Prediction Using Machine Learning",
    "seo_meta_description": "Affordable Customer Spending Prediction project using Python, Pandas and Scikit-learn for CSE, IT, BCA and MCA final-year students.",
    "active": true
  },
  {
    "title": "Air Quality Prediction & Analysis Using Machine Learning",
    "slug": "air-quality-prediction-analysis-machine-learning",
    "category": "Data Science",
    "department": "CSE, IT, ECE, BCA, MCA",
    "difficulty": "Basic",
    "starting_price": 1499,
    "technologies": [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Matplotlib",
      "Seaborn",
      "Machine Learning",
      "Data Visualization",
      "Streamlit"
    ],
    "short_description": "A data science system that analyzes air pollution data and predicts air quality based on environmental parameters.",
    "description": "Air Quality Prediction & Analysis is a data science project designed to analyze pollution levels and predict air quality using historical environmental data. The system examines parameters such as temperature, humidity, particulate matter, and pollutant concentrations.",
    "problem_statement": "Monitoring and understanding air quality can be difficult because pollution levels vary across locations and time.",
    "proposed_solution": "Develop a machine learning-based system that analyzes historical environmental data and predicts air quality while providing useful visual insights.",
    "features": [
      "Air quality data management",
      "Data preprocessing",
      "Pollutant analysis",
      "Temperature analysis",
      "Humidity analysis",
      "Air quality prediction",
      "Historical trend analysis",
      "Location-based analysis",
      "Data visualization",
      "Model evaluation",
      "Interactive dashboard",
      "Air quality reporting"
    ],
    "architecture": "Environmental data is collected and cleaned using Pandas and NumPy. Relevant features are analyzed and used to train machine learning models using Scikit-learn. The prediction results and historical trends are displayed through an interactive Streamlit dashboard.",
    "seo_title": "Air Quality Prediction Using Machine Learning Project",
    "seo_meta_description": "Affordable Air Quality Prediction project using Python, Pandas, Scikit-learn and machine learning for CSE, IT, ECE, BCA and MCA students.",
    "active": true
  },
  {
    "title": "Weather Forecasting & Analysis Using Machine Learning",
    "slug": "weather-forecasting-analysis-machine-learning",
    "category": "Data Science",
    "department": "CSE, IT, ECE, BCA, MCA",
    "difficulty": "Basic",
    "starting_price": 1499,
    "technologies": [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Matplotlib",
      "Seaborn",
      "Machine Learning",
      "Data Visualization",
      "Streamlit"
    ],
    "short_description": "A machine learning-based system that analyzes historical weather patterns and predicts weather conditions using environmental data.",
    "description": "Weather Forecasting & Analysis uses historical weather data to identify patterns in temperature, humidity, rainfall, wind speed, and atmospheric conditions. Machine learning techniques are used to generate predictions based on historical observations.",
    "problem_statement": "Weather conditions change continuously, and analyzing historical patterns manually is difficult when dealing with large datasets.",
    "proposed_solution": "Develop a machine learning system that analyzes historical weather data and generates predictions while providing visual insights into weather trends.",
    "features": [
      "Weather data management",
      "Data preprocessing",
      "Temperature analysis",
      "Humidity analysis",
      "Rainfall analysis",
      "Wind speed analysis",
      "Weather prediction",
      "Historical trend visualization",
      "Seasonal analysis",
      "Model evaluation",
      "Interactive dashboard",
      "Weather reports"
    ],
    "architecture": "Historical weather data is collected and preprocessed using Pandas and NumPy. Features are selected and supplied to Scikit-learn machine learning models. The prediction results are displayed through a Streamlit dashboard along with weather trend visualizations.",
    "seo_title": "Weather Forecasting Using Machine Learning Project",
    "seo_meta_description": "Affordable Weather Forecasting project using Python, Pandas, Scikit-learn and machine learning for CSE, IT, ECE, BCA and MCA students.",
    "active": true
  },
  {
    "title": "Student Dropout Prediction Using Machine Learning",
    "slug": "student-dropout-prediction-machine-learning",
    "category": "AI/ML",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Intermediate",
    "starting_price": 1999,
    "technologies": [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Matplotlib",
      "Seaborn",
      "Machine Learning",
      "Classification",
      "Streamlit"
    ],
    "short_description": "A machine learning system that identifies students who may be at risk of dropping out based on academic, attendance, and demographic factors.",
    "description": "Student Dropout Prediction is an AI/ML project designed to identify students who may be at risk of discontinuing their education. The system analyzes factors such as attendance, academic performance, previous results, financial conditions, and engagement indicators.",
    "problem_statement": "Educational institutions may struggle to identify students at risk of dropping out early enough to provide appropriate support.",
    "proposed_solution": "Develop a classification model that analyzes historical student data and identifies students who may have a higher risk of dropping out.",
    "features": [
      "Student data management",
      "Academic performance analysis",
      "Attendance analysis",
      "Student engagement analysis",
      "Risk factor identification",
      "Dropout prediction",
      "Risk classification",
      "Machine learning model",
      "Model evaluation",
      "Feature importance",
      "Risk dashboard",
      "Student risk reports"
    ],
    "architecture": "Student information is collected and preprocessed using Pandas and NumPy. Relevant academic and behavioral features are provided to classification models using Scikit-learn. The trained model predicts dropout risk, which is displayed through an interactive dashboard.",
    "seo_title": "Student Dropout Prediction Using Machine Learning",
    "seo_meta_description": "Student Dropout Prediction project using Python, Pandas, Scikit-learn and machine learning for CSE, IT, BCA and MCA final-year students.",
    "active": true
  },
  {
    "title": "Credit Risk Prediction System Using Machine Learning",
    "slug": "credit-risk-prediction-machine-learning",
    "category": "AI/ML",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Intermediate",
    "starting_price": 2499,
    "technologies": [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Matplotlib",
      "Seaborn",
      "Machine Learning",
      "Classification",
      "Streamlit"
    ],
    "short_description": "A machine learning system that analyzes financial and customer information to classify potential credit risk.",
    "description": "Credit Risk Prediction analyzes applicant information such as income, credit history, loan details, repayment behavior, and financial characteristics. A machine learning classification model learns from historical data and categorizes applicants according to predefined risk levels.",
    "problem_statement": "Financial institutions need efficient methods to assess credit risk, but analyzing multiple financial factors manually can be time-consuming.",
    "proposed_solution": "Develop a machine learning-based credit risk classification system that analyzes applicant information and predicts predefined credit risk categories.",
    "features": [
      "Customer data management",
      "Financial data preprocessing",
      "Credit history analysis",
      "Income analysis",
      "Loan analysis",
      "Risk classification",
      "Credit risk prediction",
      "Feature importance analysis",
      "Model training",
      "Model evaluation",
      "Risk visualization",
      "Interactive dashboard"
    ],
    "architecture": "Financial data is cleaned and transformed using Pandas and NumPy. Relevant features are encoded and provided to Scikit-learn classification models. The trained model predicts the predefined risk category, while Streamlit provides the interactive user interface.",
    "seo_title": "Credit Risk Prediction Using Machine Learning Project",
    "seo_meta_description": "Affordable Credit Risk Prediction project using Python, Pandas, Scikit-learn and machine learning for final-year CSE, IT, BCA and MCA students.",
    "active": true
  },
  {
    "title": "Demand Forecasting System Using Machine Learning",
    "slug": "demand-forecasting-system-machine-learning",
    "category": "Data Science",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Intermediate",
    "starting_price": 2999,
    "technologies": [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Matplotlib",
      "Seaborn",
      "Machine Learning",
      "Time Series Analysis",
      "Streamlit"
    ],
    "short_description": "A machine learning system that analyzes historical demand patterns and forecasts future product demand.",
    "description": "Demand Forecasting System is designed to estimate future demand using historical sales and transaction data. The system analyzes product demand, seasonal patterns, sales trends, and historical purchasing behavior to generate future demand estimates.",
    "problem_statement": "Businesses need accurate demand estimates to manage inventory and resources, but forecasting manually can be difficult.",
    "proposed_solution": "Develop a machine learning-based forecasting system that learns from historical demand patterns and predicts future product requirements.",
    "features": [
      "Sales data management",
      "Demand data preprocessing",
      "Historical demand analysis",
      "Product-wise demand analysis",
      "Seasonal trend analysis",
      "Time series analysis",
      "Demand forecasting",
      "Forecast visualization",
      "Model evaluation",
      "Future demand estimation",
      "Interactive dashboard",
      "Forecast reports"
    ],
    "architecture": "Historical demand data is processed using Pandas and NumPy. Time-based and product-related features are extracted and used for machine learning or forecasting models. Predictions are evaluated and presented through an interactive Streamlit dashboard.",
    "seo_title": "Demand Forecasting Using Machine Learning Project",
    "seo_meta_description": "Affordable Demand Forecasting project using Python, Pandas, Scikit-learn and time series analysis for final-year students.",
    "active": true
  },
  {
    "title": "Energy Consumption Prediction Using Machine Learning",
    "slug": "energy-consumption-prediction-machine-learning",
    "category": "AI/ML",
    "department": "CSE, IT, ECE, BCA, MCA",
    "difficulty": "Intermediate",
    "starting_price": 3499,
    "technologies": [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Matplotlib",
      "Seaborn",
      "Machine Learning",
      "Regression",
      "Time Series",
      "Streamlit"
    ],
    "short_description": "A machine learning system that predicts energy consumption using historical usage patterns and environmental factors.",
    "description": "Energy Consumption Prediction analyzes historical energy usage data to estimate future consumption. The system considers factors such as time, temperature, usage patterns, and historical energy consumption.",
    "problem_statement": "Predicting energy requirements accurately is important for efficient resource planning, but consumption patterns can vary significantly over time.",
    "proposed_solution": "Develop a machine learning model that learns from historical energy usage patterns and predicts future energy consumption.",
    "features": [
      "Energy data management",
      "Data preprocessing",
      "Consumption trend analysis",
      "Daily consumption analysis",
      "Monthly consumption analysis",
      "Peak usage identification",
      "Energy consumption prediction",
      "Time series analysis",
      "Model evaluation",
      "Usage visualization",
      "Forecast generation",
      "Interactive dashboard"
    ],
    "architecture": "Energy consumption data is collected and processed using Pandas and NumPy. Time-based and environmental features are extracted and supplied to regression or forecasting models using Scikit-learn. Predictions are visualized through an interactive Streamlit dashboard.",
    "seo_title": "Energy Consumption Prediction Using Machine Learning",
    "seo_meta_description": "Energy Consumption Prediction project using Python, Pandas, Scikit-learn and machine learning for CSE, IT, ECE, BCA and MCA students.",
    "active": true
  },
  {
    "title": "Predictive Maintenance System Using Machine Learning",
    "slug": "predictive-maintenance-system-machine-learning",
    "category": "AI/ML",
    "department": "CSE, IT, ECE",
    "difficulty": "Advanced",
    "starting_price": 4499,
    "technologies": [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Matplotlib",
      "Seaborn",
      "Machine Learning",
      "Classification",
      "Predictive Analytics",
      "Streamlit"
    ],
    "short_description": "An AI-based predictive maintenance system that analyzes equipment data to identify potential machine failures before they occur.",
    "description": "Predictive Maintenance uses machine learning to analyze equipment and sensor data and identify patterns associated with potential failures. The system can process information such as temperature, vibration, pressure, operating hours, and equipment status.",
    "problem_statement": "Unexpected equipment failures can cause downtime, maintenance costs, and operational disruptions.",
    "proposed_solution": "Develop a machine learning-based predictive maintenance system that analyzes equipment data and predicts potential failure conditions, allowing maintenance activities to be planned proactively.",
    "features": [
      "Equipment data management",
      "Sensor data processing",
      "Data preprocessing",
      "Temperature monitoring",
      "Vibration analysis",
      "Pressure monitoring",
      "Equipment health analysis",
      "Failure prediction",
      "Risk classification",
      "Predictive analytics",
      "Maintenance alerts",
      "Performance dashboard",
      "Historical failure analysis"
    ],
    "architecture": "Equipment and sensor data is collected and processed using Python, Pandas, and NumPy. Relevant features are extracted and passed to machine learning classification models using Scikit-learn. The model predicts predefined equipment status or failure-risk categories. A Streamlit dashboard displays equipment health, predictions, and analytics.",
    "seo_title": "Predictive Maintenance Using Machine Learning Project",
    "seo_meta_description": "Advanced Predictive Maintenance project using Python, Scikit-learn, machine learning and predictive analytics for CSE and ECE final-year students.",
    "active": true
  },
  {
    "title": "Anomaly Detection & Monitoring System Using Machine Learning",
    "slug": "anomaly-detection-monitoring-system",
    "category": "AI/ML",
    "department": "CSE, IT, ECE",
    "difficulty": "Advanced",
    "starting_price": 4999,
    "technologies": [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Matplotlib",
      "Seaborn",
      "Machine Learning",
      "Anomaly Detection",
      "Isolation Forest",
      "Streamlit"
    ],
    "short_description": "An AI-based monitoring system that identifies unusual patterns and abnormal behavior in large datasets.",
    "description": "The Anomaly Detection & Monitoring System uses machine learning techniques to identify unusual observations in structured data. The system can be applied to areas such as system monitoring, transactions, equipment data, network activity, and operational metrics.",
    "problem_statement": "Unusual activities and abnormal patterns can be difficult to identify manually when monitoring large volumes of continuously generated data.",
    "proposed_solution": "Develop an anomaly detection system that learns normal data patterns and identifies observations that significantly differ from expected behavior.",
    "features": [
      "Data ingestion",
      "Data preprocessing",
      "Normal behavior analysis",
      "Anomaly detection",
      "Outlier identification",
      "Isolation Forest model",
      "Anomaly scoring",
      "Threshold configuration",
      "Anomaly visualization",
      "Historical anomaly analysis",
      "Monitoring dashboard",
      "Alert generation"
    ],
    "architecture": "Data is collected from structured sources and processed using Pandas and NumPy. Machine learning algorithms such as Isolation Forest are used to identify unusual observations. Detected anomalies are assigned scores and displayed through an interactive monitoring dashboard built with Streamlit.",
    "seo_title": "Anomaly Detection Using Machine Learning Project",
    "seo_meta_description": "Advanced Anomaly Detection project using Python, Scikit-learn, Isolation Forest and machine learning for CSE, IT and ECE final-year students.",
    "active": true
  },
  {
    "title": "AI-Powered Business Intelligence & Analytics System",
    "slug": "ai-powered-business-intelligence-analytics",
    "category": "Analytics",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Advanced",
    "starting_price": 5999,
    "technologies": [
      "Python",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "SQL",
      "Power BI",
      "Machine Learning",
      "Data Analytics",
      "Data Visualization",
      "Streamlit"
    ],
    "short_description": "An AI-powered business intelligence platform that combines data analytics, machine learning, KPI monitoring, and interactive dashboards to generate actionable business insights.",
    "description": "The AI-Powered Business Intelligence System combines data analytics and machine learning to transform business data into meaningful insights. The system can analyze sales, customer, financial, operational, and performance data to identify trends, patterns, anomalies, and important business metrics.\n\nInteractive dashboards provide KPI monitoring, historical analysis, predictive insights, and visual reports. Machine learning models can be integrated to support forecasting and predictive analytics.",
    "problem_statement": "Organizations generate large amounts of business data but often struggle to convert raw information into timely and meaningful insights for decision-making.",
    "proposed_solution": "Develop an AI-powered business intelligence platform that integrates data processing, analytics, machine learning, visualization, and KPI monitoring into a centralized system.",
    "features": [
      "Multi-source data integration",
      "Data preprocessing",
      "SQL-based data analysis",
      "KPI monitoring",
      "Sales analytics",
      "Customer analytics",
      "Financial analytics",
      "Business trend analysis",
      "Predictive analytics",
      "Anomaly detection",
      "Forecasting",
      "Interactive dashboards",
      "Power BI integration",
      "AI-generated business insights",
      "Reports and visualization"
    ],
    "architecture": "The system follows a multi-layer analytics architecture consisting of data sources, data processing, analytics, machine learning, visualization, and reporting modules. Data from CSV, Excel, SQL databases, or other structured sources is processed using Python, Pandas, and NumPy. SQL is used for querying and aggregation, while machine learning models provide predictive and anomaly-detection capabilities. Power BI and Streamlit provide interactive dashboards for KPI monitoring, business analysis, and visualization.",
    "seo_title": "AI-Powered Business Intelligence & Analytics Project",
    "seo_meta_description": "Advanced AI-powered Business Intelligence project using Python, SQL, Power BI, machine learning and data analytics for CSE, IT, BCA and MCA final-year students.",
    "active": true
  }
];
