export const projectsData = [
  {
    title: "Student Management System",
    slug: "student-management-system",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Basic",
    starting_price: 1499,
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap", "Node.js", "Express.js", "MongoDB"],
    short_description: "A full-stack web application for managing student profiles, academic records, attendance, and other student information.",
    description: "Student Management System is a web-based application designed to simplify the management of student information in educational institutions. Administrators and authorized users can add, update, search, and manage student records through a centralized dashboard.",
    problem_statement: "Managing student information manually using spreadsheets or paper records can be time-consuming, difficult to maintain, and prone to errors.",
    proposed_solution: "Develop a centralized full-stack web application that allows authorized users to securely manage student information and academic records.",
    features: [
      "User authentication",
      "Admin dashboard",
      "Student registration",
      "Student profile management",
      "Add and update student records",
      "Search and filter students",
      "Attendance management",
      "Academic record management",
      "Student deletion",
      "Database management",
      "Responsive interface"
    ],
    architecture: "The application uses a client-server architecture. The frontend provides the user interface, while the Node.js and Express.js backend handles business logic and REST APIs. MongoDB stores student and user information.",
    seo_title: "Student Management System Full Stack Project",
    seo_description: "Affordable Student Management System full-stack project using HTML, CSS, JavaScript, Node.js, Express.js and MongoDB for final-year students."
  },
  {
    title: "Online Library Management System",
    slug: "online-library-management-system",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Basic",
    starting_price: 1499,
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap", "Node.js", "Express.js", "MongoDB"],
    short_description: "A full-stack library management application for managing books, students, borrowing records, returns, and library transactions.",
    description: "The Online Library Management System provides a centralized platform for managing library resources and transactions. Administrators can manage books, members, issue and return records, and monitor available books through a web-based dashboard.",
    problem_statement: "Manual library management makes it difficult to track book availability, borrowing records, return dates, and member information efficiently.",
    proposed_solution: "Create a web-based library management system that digitizes book and member management and provides efficient tracking of borrowing and returning activities.",
    features: [
      "Admin login",
      "Book registration",
      "Book search",
      "Book availability tracking",
      "Student/member management",
      "Book issue management",
      "Book return management",
      "Due date tracking",
      "Transaction history",
      "Dashboard",
      "Responsive design"
    ],
    architecture: "The frontend communicates with a Node.js and Express.js backend through REST APIs. MongoDB stores book, member, and transaction information. The application provides separate functionality for administrators and library users.",
    seo_title: "Online Library Management System Full Stack Project",
    seo_description: "Online Library Management System project using Node.js, Express.js, MongoDB and JavaScript for CSE, IT, BCA and MCA students."
  },
  {
    title: "Online Food Ordering Website",
    slug: "online-food-ordering-website",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Intermediate",
    starting_price: 2499,
    technologies: ["HTML", "CSS", "JavaScript", "React", "Node.js", "Express.js", "MongoDB", "REST API"],
    short_description: "A full-stack food ordering platform that allows customers to browse menus, add food items to a cart, place orders, and track order status.",
    description: "The Online Food Ordering Website is a complete web application that connects customers with restaurants through an interactive ordering platform. Users can browse food items, view prices, manage their cart, place orders, and check order status. Administrators can manage food items and customer orders.",
    problem_statement: "Traditional food ordering methods can be inconvenient for customers and difficult for restaurants to manage efficiently.",
    proposed_solution: "Develop a centralized online platform that provides digital menu browsing, cart management, order processing, and order tracking.",
    features: [
      "User registration and login",
      "Restaurant/menu management",
      "Food item search",
      "Category filtering",
      "Shopping cart",
      "Order placement",
      "Order history",
      "Order status tracking",
      "Admin dashboard",
      "Food item management",
      "Responsive design"
    ],
    architecture: "React provides the frontend interface, while Node.js and Express.js handle backend APIs and business logic. MongoDB stores users, products, carts, and orders. REST APIs connect the frontend and backend.",
    seo_title: "Online Food Ordering Website Full Stack Project",
    seo_description: "Affordable Online Food Ordering Website project using React, Node.js, Express.js and MongoDB for final-year engineering students."
  },
  {
    title: "E-Commerce Website",
    slug: "e-commerce-website-full-stack",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Intermediate",
    starting_price: 2999,
    technologies: ["React", "HTML", "CSS", "JavaScript", "Node.js", "Express.js", "MongoDB", "REST API", "Bootstrap"],
    short_description: "A complete e-commerce web application with product browsing, search, shopping cart, user authentication, order management, and an admin dashboard.",
    description: "The E-Commerce Website is a full-stack online shopping platform where users can browse products, view product details, add products to a cart, place orders, and manage their accounts. Administrators can manage products, categories, inventory, and customer orders.",
    problem_statement: "Small businesses and organizations need affordable digital platforms to showcase products and manage online sales.",
    proposed_solution: "Build a complete e-commerce platform with customer and administrator modules for managing products and online orders.",
    features: [
      "User registration and login",
      "Product listing",
      "Product search",
      "Category filtering",
      "Product details",
      "Shopping cart",
      "Wishlist",
      "Order placement",
      "Order history",
      "Admin dashboard",
      "Product management",
      "Inventory management",
      "Order management",
      "Responsive design"
    ],
    architecture: "The system follows a three-layer architecture consisting of React frontend, Node.js/Express.js backend, and MongoDB database. REST APIs handle communication between the frontend and backend.",
    seo_title: "E-Commerce Website Full Stack Project",
    seo_description: "Complete E-Commerce Website project using React, Node.js, Express.js and MongoDB for CSE, IT, BCA and MCA final-year students."
  },
  {
    title: "Online Course Management System",
    slug: "online-course-management-system",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Intermediate",
    starting_price: 2499,
    technologies: ["React", "JavaScript", "Node.js", "Express.js", "MongoDB", "HTML", "CSS", "REST API"],
    short_description: "A full-stack learning platform for managing courses, instructors, students, lessons, enrollments, and learning progress.",
    description: "The Online Course Management System provides a digital platform where students can browse and enroll in courses while instructors can manage course content. Administrators can manage users, courses, and platform activities.",
    problem_statement: "Managing online learning content and student enrollments manually can become difficult as the number of courses and learners increases.",
    proposed_solution: "Develop a centralized course management platform that enables administrators and instructors to manage courses while students can access enrolled learning content.",
    features: [
      "Student registration",
      "Instructor registration",
      "Course creation",
      "Course listing",
      "Course enrollment",
      "Lesson management",
      "Learning progress tracking",
      "Student dashboard",
      "Instructor dashboard",
      "Admin dashboard",
      "Search and filtering",
      "User management"
    ],
    architecture: "React is used for the frontend and Node.js with Express.js provides backend services. MongoDB stores users, courses, lessons, and enrollment information. REST APIs enable communication between application components.",
    seo_title: "Online Course Management System Full Stack Project",
    seo_description: "Online Course Management System using React, Node.js, Express.js and MongoDB for final-year CSE, IT, BCA and MCA projects."
  },
  {
    title: "College Event Management System",
    slug: "college-event-management-system",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Basic",
    starting_price: 1999,
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap", "Node.js", "Express.js", "MongoDB"],
    short_description: "A web-based platform for creating, managing, promoting, and registering for college events.",
    description: "The College Event Management System helps institutions organize technical events, cultural programs, workshops, seminars, and competitions. Students can browse upcoming events and register online, while administrators can manage events and registrations.",
    problem_statement: "Managing college events through manual registration and communication methods can result in inefficient record keeping and poor coordination.",
    proposed_solution: "Create a centralized event management platform that simplifies event creation, student registration, communication, and participation tracking.",
    features: [
      "User registration",
      "Admin login",
      "Event creation",
      "Event listing",
      "Event search",
      "Online registration",
      "Participant management",
      "Event schedule",
      "Registration history",
      "Admin dashboard",
      "Responsive interface"
    ],
    architecture: "The system consists of a responsive frontend, Node.js/Express.js backend, and MongoDB database. APIs manage event and participant information between the frontend and backend.",
    seo_title: "College Event Management System Full Stack Project",
    seo_description: "College Event Management System using JavaScript, Node.js, Express.js and MongoDB for final-year students."
  },
  {
    title: "Online Complaint Management System",
    slug: "online-complaint-management-system",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Basic",
    starting_price: 1499,
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap", "Node.js", "Express.js", "MongoDB"],
    short_description: "A web-based platform that allows users to submit complaints, track their status, and receive updates from administrators.",
    description: "The Online Complaint Management System provides a centralized platform for submitting and managing complaints. Users can create complaints and monitor their progress, while administrators can review complaints, assign priorities, update statuses, and manage resolutions.",
    problem_statement: "Manual complaint handling can cause delays, poor tracking, and difficulty in maintaining complaint records.",
    proposed_solution: "Develop an online complaint management system that digitizes complaint submission, tracking, assignment, and resolution.",
    features: [
      "User registration",
      "Complaint submission",
      "Complaint categorization",
      "Priority management",
      "Complaint tracking",
      "Status updates",
      "Admin dashboard",
      "Complaint assignment",
      "Resolution management",
      "Complaint history",
      "Search and filtering"
    ],
    architecture: "The frontend communicates with a Node.js and Express.js backend through REST APIs. MongoDB stores user, complaint, and status information.",
    seo_title: "Online Complaint Management System Full Stack Project",
    seo_description: "Affordable Online Complaint Management System using Node.js, Express.js and MongoDB for CSE, IT, BCA and MCA students."
  },
  {
    title: "Job Portal Website",
    slug: "job-portal-website-full-stack",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Intermediate",
    starting_price: 2999,
    technologies: ["React", "JavaScript", "Node.js", "Express.js", "MongoDB", "REST API", "HTML", "CSS"],
    short_description: "A full-stack job portal that connects job seekers and recruiters through job posting, searching, applications, and profile management.",
    description: "The Job Portal Website provides a centralized platform where job seekers can create profiles, search for suitable job opportunities, and apply for positions. Recruiters can create company profiles, post jobs, review applications, and manage candidates.",
    problem_statement: "Job seekers and recruiters often use multiple platforms to manage job searches and recruitment activities.",
    proposed_solution: "Build a centralized job portal that provides job discovery, applications, recruiter management, and candidate tracking.",
    features: [
      "Job seeker registration",
      "Recruiter registration",
      "User authentication",
      "Job posting",
      "Job search",
      "Job filtering",
      "Job application",
      "Resume upload",
      "Application tracking",
      "Recruiter dashboard",
      "Candidate management",
      "Company profile",
      "Admin dashboard"
    ],
    architecture: "The application uses React for the frontend and Node.js/Express.js for backend services. MongoDB stores users, jobs, companies, resumes, and applications. REST APIs connect the frontend with backend services.",
    seo_title: "Job Portal Website Full Stack Project",
    seo_description: "Job Portal Website using React, Node.js, Express.js and MongoDB for CSE, IT, BCA and MCA final-year projects."
  },
  {
    title: "Online Hospital Appointment System",
    slug: "online-hospital-appointment-system",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Intermediate",
    starting_price: 2499,
    technologies: ["React", "JavaScript", "Node.js", "Express.js", "MongoDB", "HTML", "CSS", "REST API"],
    short_description: "A full-stack healthcare appointment platform for finding doctors, booking appointments, and managing schedules.",
    description: "The Online Hospital Appointment System allows patients to browse doctors, view available appointment slots, and submit appointment requests. Hospital administrators can manage doctors, schedules, appointments, and patient information.",
    problem_statement: "Manual appointment booking can result in long waiting times, scheduling conflicts, and inefficient record management.",
    proposed_solution: "Develop an online appointment platform that allows patients to conveniently book appointments while enabling hospital staff to manage schedules and bookings.",
    features: [
      "Patient registration",
      "Doctor registration",
      "Doctor listing",
      "Specialization filtering",
      "Appointment booking",
      "Appointment scheduling",
      "Appointment status",
      "Patient dashboard",
      "Doctor dashboard",
      "Admin dashboard",
      "Appointment history",
      "Schedule management"
    ],
    architecture: "The frontend is developed using React and communicates with a Node.js/Express.js backend through REST APIs. MongoDB stores patient, doctor, schedule, and appointment information.",
    seo_title: "Online Hospital Appointment System Full Stack Project",
    seo_description: "Online Hospital Appointment System using React, Node.js, Express.js and MongoDB for final-year CSE, IT, BCA and MCA students."
  },
  {
    title: "Hostel Management System",
    slug: "hostel-management-system",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Basic",
    starting_price: 1999,
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap", "Node.js", "Express.js", "MongoDB"],
    short_description: "A web-based hostel management system for managing students, rooms, allocations, complaints, and hostel records.",
    description: "The Hostel Management System provides a centralized platform for hostel administrators to manage student accommodation. The system supports room allocation, student records, complaints, and hostel occupancy information.",
    problem_statement: "Manual hostel management makes room allocation, student tracking, and complaint management difficult and time-consuming.",
    proposed_solution: "Develop a digital hostel management platform that simplifies student registration, room allocation, occupancy tracking, and complaint management.",
    features: [
      "Student registration",
      "Room management",
      "Room allocation",
      "Room availability tracking",
      "Student records",
      "Hostel occupancy dashboard",
      "Complaint submission",
      "Complaint management",
      "Admin dashboard",
      "Search and filtering"
    ],
    architecture: "The system uses a client-server architecture with a JavaScript-based frontend and Node.js/Express.js backend. MongoDB stores student, room, allocation, and complaint information.",
    seo_title: "Hostel Management System Full Stack Project",
    seo_description: "Hostel Management System using HTML, CSS, JavaScript, Node.js, Express.js and MongoDB for final-year students."
  },
  {
    title: "Online Examination System",
    slug: "online-examination-system",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Intermediate",
    starting_price: 2499,
    technologies: ["React", "JavaScript", "Node.js", "Express.js", "MongoDB", "HTML", "CSS"],
    short_description: "An online examination platform for creating tests, managing questions, conducting exams, and automatically generating results.",
    description: "The Online Examination System enables administrators or faculty members to create online tests and manage questions. Students can attend examinations through the web interface and receive results after submission.",
    problem_statement: "Conducting examinations manually requires significant effort for question management, evaluation, and result preparation.",
    proposed_solution: "Develop an online examination platform that automates test creation, exam participation, evaluation, and result generation.",
    features: [
      "Student login",
      "Admin login",
      "Question management",
      "Exam creation",
      "Multiple-choice questions",
      "Online exam interface",
      "Timer",
      "Automatic evaluation",
      "Result generation",
      "Score history",
      "Exam management",
      "Student dashboard",
      "Admin dashboard"
    ],
    architecture: "React provides the examination interface while Node.js and Express.js manage authentication, exams, questions, and results. MongoDB stores users, questions, exams, and scores.",
    seo_title: "Online Examination System Full Stack Project",
    seo_description: "Online Examination System using React, Node.js, Express.js and MongoDB for CSE, IT, BCA and MCA final-year students."
  },
  {
    title: "Employee Management System",
    slug: "employee-management-system",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Basic",
    starting_price: 1499,
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap", "Node.js", "Express.js", "MongoDB"],
    short_description: "A full-stack application for managing employee profiles, departments, roles, attendance, and organizational records.",
    description: "The Employee Management System provides organizations with a centralized platform for maintaining employee information. Administrators can add employees, manage departments, update employee details, and monitor organizational records.",
    problem_statement: "Managing employee records manually can result in duplicate information, outdated records, and difficulty accessing employee details.",
    proposed_solution: "Develop a centralized employee management platform that simplifies employee data storage, organization, searching, and updating.",
    features: [
      "Admin authentication",
      "Employee registration",
      "Employee profile management",
      "Department management",
      "Role management",
      "Employee search",
      "Employee filtering",
      "Attendance records",
      "Employee status management",
      "Dashboard"
    ],
    architecture: "The application consists of a frontend interface, Node.js/Express.js backend, and MongoDB database. REST APIs are used to manage employee records and administrative operations.",
    seo_title: "Employee Management System Full Stack Project",
    seo_description: "Employee Management System using JavaScript, Node.js, Express.js and MongoDB for CSE, IT, BCA and MCA final-year projects."
  },
  {
    title: "College Placement Management System",
    slug: "college-placement-management-system",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Intermediate",
    starting_price: 2999,
    technologies: ["React", "JavaScript", "Node.js", "Express.js", "MongoDB", "REST API", "HTML", "CSS"],
    short_description: "A full-stack platform for managing student placement profiles, companies, job drives, applications, and placement results.",
    description: "The College Placement Management System helps placement departments manage campus recruitment activities digitally. Students can create profiles and apply for eligible opportunities, while placement officers can manage companies, drives, applications, and placement records.",
    problem_statement: "Managing placement activities through spreadsheets and manual records makes it difficult to track student applications, company drives, eligibility, and final placement results.",
    proposed_solution: "Develop a centralized placement management platform that digitizes student profiles, company information, recruitment drives, applications, and placement results.",
    features: [
      "Student registration",
      "Student profile management",
      "Resume management",
      "Company registration",
      "Job drive creation",
      "Eligibility management",
      "Job application",
      "Application tracking",
      "Placement status",
      "Company dashboard",
      "Student dashboard",
      "Placement officer dashboard",
      "Reports and analytics"
    ],
    architecture: "The system uses React for the frontend, Node.js/Express.js for backend APIs, and MongoDB for storing student, company, job drive, application, and placement information.",
    seo_title: "College Placement Management System Full Stack Project",
    seo_description: "College Placement Management System using React, Node.js, Express.js and MongoDB for final-year CSE, IT, BCA and MCA students."
  },
  {
    title: "Online Attendance Management System",
    slug: "online-attendance-management-system",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Basic",
    starting_price: 1999,
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap", "Node.js", "Express.js", "MongoDB"],
    short_description: "A web-based attendance management system for recording, monitoring, and analyzing student attendance digitally.",
    description: "The Online Attendance Management System enables faculty members to record student attendance through a centralized web application. Students can view their attendance percentage and attendance history, while administrators can generate attendance reports.",
    problem_statement: "Maintaining attendance records manually is time-consuming and makes it difficult to calculate percentages and generate reports accurately.",
    proposed_solution: "Develop a digital attendance management platform that allows faculty to record attendance and students to monitor their attendance status.",
    features: [
      "Faculty login",
      "Student login",
      "Student management",
      "Class management",
      "Daily attendance recording",
      "Attendance editing",
      "Attendance percentage calculation",
      "Attendance history",
      "Subject-wise attendance",
      "Attendance reports",
      "Dashboard"
    ],
    architecture: "The frontend provides separate interfaces for faculty, students, and administrators. Node.js and Express.js handle backend operations while MongoDB stores student, subject, and attendance records.",
    seo_title: "Online Attendance Management System Full Stack Project",
    seo_description: "Online Attendance Management System using JavaScript, Node.js, Express.js and MongoDB for CSE, IT, BCA and MCA students."
  },
  {
    title: "Expense Tracker Web Application",
    slug: "expense-tracker-web-application",
    category: "Full Stack",
    department: "CSE, IT, BCA, MCA",
    difficulty: "Basic",
    starting_price: 1499,
    technologies: ["HTML", "CSS", "JavaScript", "Bootstrap", "Node.js", "Express.js", "MongoDB", "Chart.js"],
    short_description: "A full-stack expense tracking application that helps users record income and expenses, categorize transactions, and monitor their spending.",
    description: "The Expense Tracker Web Application allows users to manage their personal financial transactions through an easy-to-use web interface. Users can record income and expenses, organize transactions into categories, view spending summaries, and analyze their financial activity using charts and dashboards.",
    problem_statement: "Tracking daily income and expenses manually can make it difficult to understand spending habits and maintain accurate financial records.",
    proposed_solution: "Develop a full-stack expense management application that allows users to digitally record, categorize, monitor, and analyze their financial transactions.",
    features: [
      "User registration and login",
      "Income management",
      "Expense management",
      "Transaction categorization",
      "Add and edit transactions",
      "Delete transactions",
      "Monthly expense tracking",
      "Income and expense summary",
      "Category-wise expense analysis",
      "Spending charts",
      "Transaction history",
      "Dashboard",
      "Responsive design"
    ],
    architecture: "The application uses a client-server architecture. The frontend is developed using HTML, CSS, and JavaScript, while Node.js and Express.js provide backend APIs. MongoDB stores user and transaction data, and Chart.js is used to visualize income and expense trends.",
    seo_title: "Expense Tracker Web Application Full Stack Project",
    seo_description: "Affordable Expense Tracker Web Application using JavaScript, Node.js, Express.js, MongoDB and Chart.js for final-year students."
  }
];
