export const projectsData = [
  {
    "title": "College Management & Information Portal",
    "slug": "college-management-information-portal",
    "category": "Web Development",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Intermediate",
    "starting_price": 2499,
    "technologies": [
      "HTML",
      "CSS",
      "JavaScript",
      "Bootstrap",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB"
    ],
    "short_description": "A comprehensive web portal for managing and presenting college information, departments, courses, faculty, facilities, events, and announcements.",
    "description": "College Management & Information Portal is a web-based platform designed to provide students, faculty, and visitors with centralized access to college-related information. The system allows administrators to manage departments, courses, faculty profiles, announcements, events, facilities, and other institutional content.",
    "problem_statement": "College information is often distributed across different platforms, making it difficult for students and visitors to quickly access updated institutional information.",
    "proposed_solution": "Develop a centralized responsive web portal that organizes college information and provides administrators with an easy-to-use content management system.",
    "features": [
      "Admin authentication",
      "College information management",
      "Department management",
      "Course information",
      "Faculty profiles",
      "Campus facilities",
      "Event management",
      "News and announcements",
      "Gallery management",
      "Contact information",
      "Search functionality",
      "Responsive design",
      "Admin dashboard"
    ],
    "architecture": "The system uses a client-server architecture with React for the frontend, Node.js and Express.js for backend services, and MongoDB for data storage. REST APIs connect the frontend with backend services, while the admin dashboard provides content management functionality.",
    "seo_title": "College Management & Information Portal Project",
    "seo_meta_description": "College Management and Information Portal using React, Node.js, Express.js and MongoDB for CSE, IT, BCA and MCA final-year students.",
    "active": true
  },
  {
    "title": "Online Learning & Resource Portal",
    "slug": "online-learning-resource-portal",
    "category": "Web Development",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Intermediate",
    "starting_price": 2499,
    "technologies": [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Bootstrap"
    ],
    "short_description": "A web-based learning platform that provides students with organized study materials, notes, tutorials, resources, and educational content.",
    "description": "The Online Learning & Resource Portal provides students with a centralized platform to access educational resources. Administrators or faculty members can upload and organize notes, PDFs, tutorials, videos, links, and other learning materials based on subjects or categories.",
    "problem_statement": "Students often depend on multiple platforms to find study materials, making it difficult to organize and access relevant academic resources.",
    "proposed_solution": "Develop a centralized learning resource portal where educational content can be categorized, searched, and accessed through a responsive web interface.",
    "features": [
      "Student registration",
      "User authentication",
      "Resource management",
      "Subject-wise categorization",
      "Study material upload",
      "PDF resource management",
      "Video resource links",
      "Search functionality",
      "Resource filtering",
      "Download resources",
      "Admin dashboard",
      "Responsive interface"
    ],
    "architecture": "React provides the frontend interface while Node.js and Express.js handle authentication, resource management, and API operations. MongoDB stores user and resource metadata. The system provides separate user and administrator functionalities.",
    "seo_title": "Online Learning & Resource Portal Project",
    "seo_meta_description": "Online Learning and Resource Portal using React, Node.js, Express.js and MongoDB for final-year CSE, IT, BCA and MCA students.",
    "active": true
  },
  {
    "title": "Real Estate Property Management Portal",
    "slug": "real-estate-property-management-portal",
    "category": "Web Development",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Intermediate",
    "starting_price": 2499,
    "technologies": [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Bootstrap"
    ],
    "short_description": "A property listing platform for managing, searching, and displaying residential and commercial properties with detailed information.",
    "description": "The Real Estate Property Management Portal allows property owners or agents to publish property listings with details such as location, price, property type, area, amenities, and images. Users can search and filter properties based on their requirements.",
    "problem_statement": "Finding suitable properties can be difficult when property information is scattered across different sources.",
    "proposed_solution": "Develop a centralized property listing platform that allows users to discover properties while enabling administrators or agents to manage listings efficiently.",
    "features": [
      "User registration",
      "Property listing",
      "Property details",
      "Property image management",
      "Property search",
      "Location filtering",
      "Price filtering",
      "Property type filtering",
      "Agent management",
      "Favorite properties",
      "Contact property owner",
      "Admin dashboard",
      "Responsive design"
    ],
    "architecture": "The system uses React for the frontend and Node.js/Express.js for backend APIs. MongoDB stores user, property, and agent information. REST APIs manage property listings, searches, and user interactions.",
    "seo_title": "Real Estate Property Management Portal Project",
    "seo_meta_description": "Real Estate Property Management Portal using React, Node.js, Express.js and MongoDB for final-year students.",
    "active": true
  },
  {
    "title": "Travel & Tourism Management Portal",
    "slug": "travel-tourism-management-portal",
    "category": "Web Development",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Intermediate",
    "starting_price": 2499,
    "technologies": [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Bootstrap"
    ],
    "short_description": "A tourism website for exploring destinations, travel packages, attractions, itineraries, and travel-related information.",
    "description": "The Travel & Tourism Management Portal provides users with information about tourist destinations, travel packages, attractions, hotels, and suggested itineraries. Administrators can manage destinations, packages, images, and tourism-related content.",
    "problem_statement": "Travelers often need to search multiple platforms to collect information about destinations, packages, attractions, and travel plans.",
    "proposed_solution": "Develop a centralized tourism platform that organizes destination information and provides users with an easy way to explore travel packages and plan trips.",
    "features": [
      "User registration",
      "Destination management",
      "Tour package management",
      "Destination search",
      "Category filtering",
      "Travel package details",
      "Tourist attraction information",
      "Image gallery",
      "Itinerary management",
      "User inquiries",
      "Admin dashboard",
      "Responsive design"
    ],
    "architecture": "The frontend is developed using React and communicates with a Node.js/Express.js backend through REST APIs. MongoDB stores destinations, packages, users, and inquiries. The application provides separate administrative and user interfaces.",
    "seo_title": "Travel & Tourism Management Portal Project",
    "seo_meta_description": "Travel and Tourism Management Portal using React, Node.js, Express.js and MongoDB for CSE, IT, BCA and MCA final-year projects.",
    "active": true
  },
  {
    "title": "Event Management & Registration Portal",
    "slug": "event-management-registration-portal",
    "category": "Web Development",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Intermediate",
    "starting_price": 2499,
    "technologies": [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Bootstrap"
    ],
    "short_description": "A web-based platform for creating events, managing registrations, publishing schedules, and tracking participants.",
    "description": "The Event Management & Registration Portal helps organizations and institutions create and manage events digitally. Users can browse upcoming events, view event details, register online, and monitor their registrations.",
    "problem_statement": "Manual event registration and participant management can lead to duplicate records, communication difficulties, and inefficient tracking.",
    "proposed_solution": "Develop a centralized event platform that simplifies event creation, online registration, participant management, and event reporting.",
    "features": [
      "User registration",
      "Admin authentication",
      "Event creation",
      "Event scheduling",
      "Event categories",
      "Online registration",
      "Participant management",
      "Registration tracking",
      "Event announcements",
      "Event search",
      "Admin dashboard",
      "Responsive interface"
    ],
    "architecture": "The system follows a client-server architecture using React for the frontend, Node.js and Express.js for backend APIs, and MongoDB for event and participant data. The administrator manages events and registrations through a dashboard.",
    "seo_title": "Event Management & Registration Portal Project",
    "seo_meta_description": "Event Management and Registration Portal using React, Node.js, Express.js and MongoDB for final-year students.",
    "active": true
  },
  {
    "title": "Online News & Media Portal",
    "slug": "online-news-media-portal",
    "category": "Web Development",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Intermediate",
    "starting_price": 2499,
    "technologies": [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Bootstrap"
    ],
    "short_description": "A dynamic news portal for publishing, organizing, searching, and managing news articles across multiple categories.",
    "description": "The Online News & Media Portal allows administrators and authorized authors to publish news articles and organize them into categories. Users can browse the latest news, search for articles, and filter content based on categories.",
    "problem_statement": "Managing large volumes of news content manually can make publishing, organizing, and retrieving articles difficult.",
    "proposed_solution": "Develop a dynamic web-based news platform with content management, article categorization, search, and administrative features.",
    "features": [
      "User registration",
      "Admin login",
      "News article creation",
      "Article editing",
      "News categorization",
      "Latest news section",
      "Article search",
      "Category filtering",
      "Image management",
      "Author management",
      "Comments",
      "Admin dashboard",
      "Responsive design"
    ],
    "architecture": "React handles the frontend while Node.js and Express.js manage article and user APIs. MongoDB stores news articles, categories, authors, and user information. The system provides a content management dashboard for administrators.",
    "seo_title": "Online News & Media Portal Web Development Project",
    "seo_meta_description": "Online News and Media Portal using React, Node.js, Express.js and MongoDB for CSE, IT, BCA and MCA final-year students.",
    "active": true
  },
  {
    "title": "Freelancer Services Marketplace",
    "slug": "freelancer-services-marketplace",
    "category": "Web Development",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Advanced",
    "starting_price": 2999,
    "technologies": [
      "React",
      "JavaScript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "REST API",
      "HTML",
      "CSS",
      "Bootstrap"
    ],
    "short_description": "A marketplace platform connecting freelancers and clients for discovering services, submitting projects, and managing freelance work.",
    "description": "The Freelancer Services Marketplace provides a platform where freelancers can create professional profiles, showcase their skills, and publish services. Clients can search for freelancers, explore services, submit project requirements, and communicate with service providers.",
    "problem_statement": "Freelancers and clients often require a centralized platform to discover services, manage project requirements, and organize freelance work.",
    "proposed_solution": "Develop a marketplace platform that connects clients with freelancers and provides features for service discovery, project requests, and profile management.",
    "features": [
      "User registration",
      "Freelancer profiles",
      "Client profiles",
      "Skill management",
      "Service listing",
      "Service search",
      "Category filtering",
      "Project requests",
      "Proposal management",
      "Messaging system",
      "Reviews and ratings",
      "User dashboard",
      "Admin dashboard"
    ],
    "architecture": "The platform uses React for the frontend, Node.js and Express.js for backend APIs, and MongoDB for storing user, service, project, and review data. REST APIs manage communication between application modules.",
    "seo_title": "Freelancer Services Marketplace Web Development Project",
    "seo_meta_description": "Freelancer Services Marketplace using React, Node.js, Express.js and MongoDB for final-year CSE, IT, BCA and MCA projects.",
    "active": true
  },
  {
    "title": "Healthcare Information & Consultation Portal",
    "slug": "healthcare-information-consultation-portal",
    "category": "Web Development",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Advanced",
    "starting_price": 2999,
    "technologies": [
      "React",
      "JavaScript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "REST API",
      "HTML",
      "CSS",
      "Bootstrap"
    ],
    "short_description": "A healthcare web portal for accessing health information, discovering healthcare professionals, and managing consultation requests.",
    "description": "The Healthcare Information & Consultation Portal provides users with organized healthcare information and a platform for discovering healthcare professionals. Users can browse professional profiles, submit consultation requests, and manage their appointments or inquiries.",
    "problem_statement": "Users may find it difficult to locate reliable healthcare information and organize consultation requests through disconnected platforms.",
    "proposed_solution": "Develop a centralized healthcare information portal with professional profiles, consultation requests, educational resources, and administrative management features.",
    "features": [
      "User registration",
      "Professional profiles",
      "Specialization search",
      "Healthcare information",
      "Health resource management",
      "Consultation requests",
      "Appointment management",
      "User dashboard",
      "Professional dashboard",
      "Admin dashboard",
      "Search and filtering",
      "Notification management",
      "Responsive design"
    ],
    "architecture": "The application uses React for the frontend and Node.js/Express.js for backend services. MongoDB stores user, professional, resource, and consultation information. REST APIs connect the frontend with backend modules.",
    "seo_title": "Healthcare Information & Consultation Portal Project",
    "seo_meta_description": "Healthcare Information and Consultation Portal using React, Node.js, Express.js and MongoDB for final-year students.",
    "active": true
  },
  {
    "title": "Smart Complaint & Grievance Portal",
    "slug": "smart-complaint-grievance-portal",
    "category": "Web Development",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Advanced",
    "starting_price": 2999,
    "technologies": [
      "React",
      "JavaScript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "REST API",
      "HTML",
      "CSS",
      "Bootstrap"
    ],
    "short_description": "A centralized grievance management platform for submitting complaints, assigning issues, tracking progress, and managing resolutions.",
    "description": "The Smart Complaint & Grievance Portal provides an organized platform for users to submit complaints and monitor their status. Administrators can categorize complaints, assign them to responsible departments, update their progress, and maintain resolution records.",
    "problem_statement": "Manual grievance handling can cause delays, poor communication, and difficulty tracking complaints from submission to resolution.",
    "proposed_solution": "Develop a centralized grievance management portal that digitizes complaint submission, assignment, tracking, communication, and resolution.",
    "features": [
      "User registration",
      "Complaint submission",
      "Complaint categorization",
      "Priority assignment",
      "Department assignment",
      "Complaint tracking",
      "Status management",
      "Admin dashboard",
      "Department dashboard",
      "Resolution management",
      "Complaint history",
      "Search and filtering",
      "Reports and analytics"
    ],
    "architecture": "The system follows a multi-role web architecture using React for the frontend, Node.js/Express.js for backend APIs, and MongoDB for complaint and user data. Role-based dashboards provide different functionality for users, departments, and administrators.",
    "seo_title": "Smart Complaint & Grievance Portal Project",
    "seo_meta_description": "Smart Complaint and Grievance Portal using React, Node.js, Express.js and MongoDB for CSE, IT, BCA and MCA final-year projects.",
    "active": true
  },
  {
    "title": "Career Guidance & Resource Portal",
    "slug": "career-guidance-resource-portal",
    "category": "Web Development",
    "department": "CSE, IT, BCA, MCA",
    "difficulty": "Advanced",
    "starting_price": 2999,
    "technologies": [
      "React",
      "JavaScript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "REST API",
      "HTML",
      "CSS",
      "Bootstrap"
    ],
    "short_description": "A career-focused web platform providing students with career resources, learning materials, job information, skill guides, and professional development resources.",
    "description": "The Career Guidance & Resource Portal is designed to help students explore career opportunities and access useful professional development resources. The platform can provide information about career paths, required skills, learning resources, job opportunities, interview preparation, and industry-related content.",
    "problem_statement": "Students often struggle to find organized and relevant information about career paths, required skills, job opportunities, and preparation resources.",
    "proposed_solution": "Develop a centralized career guidance platform that organizes career information, learning resources, job opportunities, and preparation materials in one place.",
    "features": [
      "Student registration",
      "User authentication",
      "Career category management",
      "Career path information",
      "Skill requirement management",
      "Learning resource management",
      "Job information",
      "Interview preparation resources",
      "Resume resources",
      "Search functionality",
      "Category filtering",
      "Bookmark resources",
      "Student dashboard",
      "Admin dashboard",
      "Responsive design"
    ],
    "architecture": "The system uses React for the frontend, Node.js and Express.js for backend services, and MongoDB for storing users, career resources, skills, and job information. REST APIs provide communication between frontend and backend modules, while role-based dashboards manage platform content.",
    "seo_title": "Career Guidance & Resource Portal Project",
    "seo_meta_description": "Career Guidance and Resource Portal using React, Node.js, Express.js and MongoDB for CSE, IT, BCA and MCA final-year students.",
    "active": true
  }
];
